const quizData = {

  /* ===================== PROGRAMMING ===================== */
  programming: {
    easy: [
      { q: "Which language runs in browser?", options: ["Java", "C", "Python", "JavaScript"], answer: "JavaScript" },
      { q: "HTML is used for?", options: ["Logic", "Structure", "Database", "Styling"], answer: "Structure" },
      { q: "CSS stands for?", options: ["Creative Style Sheet", "Cascading Style Sheets", "Computer Style Sheet", "None"], answer: "Cascading Style Sheets" },
      { q: "JS file extension?", options: [".js", ".java", ".html", ".py"], answer: ".js" },
      { q: "Which is not programming language?", options: ["Python", "Java", "HTML", "C"], answer: "HTML" },
      { q: "Which symbol ends JS statement?", options: [";", ":", ".", ","], answer: ";" },
      { q: "Which keyword declares variable?", options: ["var", "int", "float", "string"], answer: "var" },
      { q: "Which is frontend?", options: ["HTML", "Node", "MySQL", "MongoDB"], answer: "HTML" },
      { q: "Which tag runs JS?", options: ["<js>", "<script>", "<code>", "<run>"], answer: "<script>" },
      { q: "Which operator compares value & type?", options: ["==", "=", "===", "!="], answer: "===" },
      { q: "Which is loop?", options: ["if", "switch", "for", "case"], answer: "for" },
      { q: "Which prints output?", options: ["print()", "log()", "console.log()", "echo"], answer: "console.log()" },
      { q: "Which is backend?", options: ["HTML", "CSS", "PHP", "XML"], answer: "PHP" },
      { q: "Which data type stores true/false?", options: ["Number", "Boolean", "String", "Object"], answer: "Boolean" },
      { q: "Which company developed Java?", options: ["Google", "Sun Microsystems", "Apple", "Microsoft"], answer: "Sun Microsystems" },
      { q: "Which is framework?", options: ["C", "Python", "React", "Java"], answer: "React" },
      { q: "Which is database?", options: ["Node", "React", "MySQL", "Angular"], answer: "MySQL" },
      { q: "Which is version control?", options: ["Docker", "AWS", "Git", "Jenkins"], answer: "Git" },
      { q: "Which is OS?", options: ["Linux", "Python", "HTML", "CSS"], answer: "Linux" },
      { q: "Which is scripting language?", options: ["C", "Java", "JavaScript", "C++"], answer: "JavaScript" }
    ],

    medium: [
      { q: "Time complexity of linear search?", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: "O(n)" },
      { q: "Which is OOP concept?", options: ["Loop", "Encapsulation", "Compiler", "Interpreter"], answer: "Encapsulation" },
      { q: "Which HTTP method creates resource?", options: ["GET", "POST", "PUT", "DELETE"], answer: "POST" },
      { q: "JS arrays start index from?", options: ["-1", "0", "1", "2"], answer: "0" },
      { q: "Which loop executes at least once?", options: ["for", "while", "do-while", "foreach"], answer: "do-while" },
      { q: "Which is NoSQL DB?", options: ["MySQL", "Oracle", "MongoDB", "Postgres"], answer: "MongoDB" },
      { q: "Which keyword creates object?", options: ["this", "new", "object", "class"], answer: "new" },
      { q: "Which Git command uploads code?", options: ["commit", "pull", "push", "clone"], answer: "push" },
      { q: "Which file manages dependencies?", options: ["index.js", "package.json", "node.js", "config.js"], answer: "package.json" },
      { q: "Which is middleware?", options: ["Express", "React", "MongoDB", "HTML"], answer: "Express" },
      { q: "Which is immutable?", options: ["Array", "Object", "String", "Function"], answer: "String" },
      { q: "Which converts JSON to object?", options: ["JSON.parse()", "JSON.stringify()", "JSON.convert()", "parse()"], answer: "JSON.parse()" },
      { q: "Which operator spreads array?", options: ["...", "*", "&", "#"], answer: "..." },
      { q: "Which is asynchronous?", options: ["setTimeout", "for", "if", "switch"], answer: "setTimeout" },
      { q: "Which keyword handles exception?", options: ["catch", "throw", "try", "All"], answer: "All" },
      { q: "Which is REST architecture?", options: ["Stateless", "Stateful", "Centralized", "Monolithic"], answer: "Stateless" },
      { q: "Which port HTTP uses?", options: ["21", "22", "80", "443"], answer: "80" },
      { q: "Which runs JS on server?", options: ["React", "Node.js", "Angular", "Vue"], answer: "Node.js" },
      { q: "Which sorting is fastest avg?", options: ["Bubble", "Selection", "Quick", "Insertion"], answer: "Quick" },
      { q: "Which is testing type?", options: ["Unit", "Loop", "Compiler", "Syntax"], answer: "Unit" }
    ],

    hard: [
      { q: "Time complexity of binary search?", options: ["O(n)", "O(log n)", "O(n²)", "O(1)"], answer: "O(log n)" },
      { q: "Which data structure uses FIFO?", options: ["Stack", "Queue", "Tree", "Graph"], answer: "Queue" },
      { q: "Which is deadlock condition?", options: ["Circular wait", "Preemption", "Starvation", "Paging"], answer: "Circular wait" },
      { q: "Which sorting is stable?", options: ["Quick", "Heap", "Merge", "Selection"], answer: "Merge" },
      { q: "REST stands for?", options: ["Remote State", "Representational State Transfer", "Resource State", "None"], answer: "Representational State Transfer" },
      { q: "Promise states?", options: ["Pending", "Resolved", "Rejected", "All"], answer: "All" },
      { q: "Which protocol secures HTTP?", options: ["FTP", "SSH", "HTTPS", "SSL"], answer: "HTTPS" },
      { q: "Which is CI tool?", options: ["Git", "Docker", "Jenkins", "AWS"], answer: "Jenkins" },
      { q: "Which hook runs once?", options: ["useState", "useEffect", "useMemo", "useRef"], answer: "useEffect" },
      { q: "Which normal form removes transitive dependency?", options: ["1NF", "2NF", "3NF", "BCNF"], answer: "3NF" },
      { q: "Which graph traversal uses queue?", options: ["DFS", "BFS", "Tree", "Heap"], answer: "BFS" },
      { q: "Which algorithm uses divide & conquer?", options: ["Bubble", "Insertion", "Merge", "Selection"], answer: "Merge" },
      { q: "Which OS scheduling is preemptive?", options: ["FCFS", "SJF", "Round Robin", "Priority"], answer: "Round Robin" },
      { q: "Which cache is fastest?", options: ["L1", "L2", "L3", "RAM"], answer: "L1" },
      { q: "Which memory is volatile?", options: ["ROM", "SSD", "RAM", "HDD"], answer: "RAM" },
      { q: "Which algorithm detects cycle?", options: ["Dijkstra", "Bellman-Ford", "Floyd", "DFS"], answer: "DFS" },
      { q: "Which port HTTPS uses?", options: ["21", "22", "80", "443"], answer: "443" },
      { q: "Which architecture uses microservices?", options: ["Monolithic", "Client-Server", "SOA", "Microservices"], answer: "Microservices" },
      { q: "Which DB supports ACID?", options: ["MongoDB", "Redis", "MySQL", "Cassandra"], answer: "MySQL" },
      { q: "Which algorithm shortest path?", options: ["DFS", "BFS", "Dijkstra", "Prim"], answer: "Dijkstra" }
    ]
  },
  cn: {
    easy: [
      { q: "Full form of LAN?", options: ["Local Area Network", "Large Area Network", "Logical Area Network", "Long Area Network"], answer: "Local Area Network" },
      { q: "Which device connects networks?", options: ["Hub", "Switch", "Router", "Repeater"], answer: "Router" },
      { q: "IP address size (IPv4)?", options: ["16-bit", "32-bit", "64-bit", "128-bit"], answer: "32-bit" },
      { q: "Which layer is physical?", options: ["Layer 1", "Layer 2", "Layer 3", "Layer 4"], answer: "Layer 1" },
      { q: "Which protocol sends emails?", options: ["SMTP", "FTP", "HTTP", "SNMP"], answer: "SMTP" },
      { q: "Which is private IP?", options: ["192.168.1.1", "8.8.8.8", "1.1.1.1", "172.217.0.1"], answer: "192.168.1.1" },
      { q: "Which uses MAC address?", options: ["Network Layer", "Data Link Layer", "Transport Layer", "Application Layer"], answer: "Data Link Layer" },
      { q: "Which protocol is connectionless?", options: ["TCP", "UDP", "HTTP", "FTP"], answer: "UDP" },
      { q: "Default port of HTTP?", options: ["21", "22", "80", "443"], answer: "80" },
      { q: "Which topology uses central hub?", options: ["Ring", "Star", "Mesh", "Bus"], answer: "Star" },
      { q: "Which is transmission media?", options: ["Router", "Fiber", "Switch", "Hub"], answer: "Fiber" },
      { q: "Which protocol resolves IP to MAC?", options: ["RARP", "ARP", "ICMP", "DNS"], answer: "ARP" },
      { q: "Which layer handles routing?", options: ["Transport", "Network", "Session", "Application"], answer: "Network" },
      { q: "Which is IPv6 size?", options: ["32", "64", "128", "256"], answer: "128" },
      { q: "Which protocol checks errors?", options: ["ICMP", "FTP", "SMTP", "HTTP"], answer: "ICMP" },
      { q: "Which device amplifies signal?", options: ["Switch", "Router", "Repeater", "Gateway"], answer: "Repeater" },
      { q: "Which uses port numbers?", options: ["Transport", "Network", "Data Link", "Physical"], answer: "Transport" },
      { q: "Which layer encrypts data?", options: ["Presentation", "Session", "Network", "Transport"], answer: "Presentation" },
      { q: "Which protocol downloads files?", options: ["FTP", "SMTP", "SNMP", "HTTP"], answer: "FTP" },
      { q: "Which is not network type?", options: ["LAN", "WAN", "MAN", "TAN"], answer: "TAN" }
    ],

    medium: [
      { q: "TCP is?", options: ["Connectionless", "Connection-oriented", "Stateless", "Broadcast"], answer: "Connection-oriented" },
      { q: "Which algorithm used in routing?", options: ["Dijkstra", "DFS", "BFS", "Prim"], answer: "Dijkstra" },
      { q: "Which layer handles flow control?", options: ["Transport", "Network", "Session", "Physical"], answer: "Transport" },
      { q: "Which protocol maps domain to IP?", options: ["DNS", "ARP", "ICMP", "SMTP"], answer: "DNS" },
      { q: "Which is class C IP range?", options: ["192-223", "128-191", "1-126", "224-239"], answer: "192-223" },
      { q: "Which uses three-way handshake?", options: ["UDP", "TCP", "HTTP", "FTP"], answer: "TCP" },
      { q: "Which device works at Layer 2?", options: ["Router", "Switch", "Gateway", "Modem"], answer: "Switch" },
      { q: "Which protocol uses port 443?", options: ["HTTP", "HTTPS", "FTP", "SMTP"], answer: "HTTPS" },
      { q: "Which is congestion control?", options: ["TCP", "UDP", "DNS", "ARP"], answer: "TCP" },
      { q: "Which topology is fault tolerant?", options: ["Bus", "Ring", "Star", "Mesh"], answer: "Mesh" },
      { q: "Which is half duplex?", options: ["Walkie-talkie", "Telephone", "Mobile", "Internet"], answer: "Walkie-talkie" },
      { q: "Which is multicast IP?", options: ["224.0.0.1", "192.168.1.1", "10.0.0.1", "8.8.8.8"], answer: "224.0.0.1" },
      { q: "Which protocol monitors network?", options: ["SNMP", "SMTP", "FTP", "HTTP"], answer: "SNMP" },
      { q: "Which uses sliding window?", options: ["TCP", "UDP", "ICMP", "ARP"], answer: "TCP" },
      { q: "Which is not OSI layer?", options: ["Presentation", "Session", "Internet", "Transport"], answer: "Internet" },
      { q: "Which layer handles segmentation?", options: ["Transport", "Network", "Data Link", "Physical"], answer: "Transport" },
      { q: "Which protocol uses echo request?", options: ["ICMP", "ARP", "DNS", "FTP"], answer: "ICMP" },
      { q: "Which device converts signals?", options: ["Router", "Modem", "Switch", "Hub"], answer: "Modem" },
      { q: "Which is network address?", options: ["192.168.1.0", "192.168.1.1", "192.168.1.2", "192.168.1.3"], answer: "192.168.1.0" },
      { q: "Which is broadcast address?", options: ["192.168.1.255", "192.168.1.0", "192.168.1.1", "192.168.1.2"], answer: "192.168.1.255" }
    ],

    hard: [
      { q: "Which causes deadlock in network?", options: ["Congestion", "Collision", "Starvation", "Loop"], answer: "Congestion" },
      { q: "Which routing is dynamic?", options: ["RIP", "Static", "Manual", "Direct"], answer: "RIP" },
      { q: "Which algorithm avoids congestion?", options: ["Leaky bucket", "Bellman-Ford", "CRC", "ARP"], answer: "Leaky bucket" },
      { q: "Which protocol ensures reliability?", options: ["UDP", "TCP", "IP", "ICMP"], answer: "TCP" },
      { q: "Which uses token passing?", options: ["Ethernet", "Token Ring", "WiFi", "ARP"], answer: "Token Ring" },
      { q: "Which OSI layer compresses data?", options: ["Presentation", "Session", "Network", "Transport"], answer: "Presentation" },
      { q: "Which routing uses hop count?", options: ["RIP", "OSPF", "BGP", "EIGRP"], answer: "RIP" },
      { q: "Which protocol uses TLS?", options: ["HTTPS", "FTP", "SMTP", "DNS"], answer: "HTTPS" },
      { q: "Which is link-state routing?", options: ["OSPF", "RIP", "BGP", "IGRP"], answer: "OSPF" },
      { q: "Which detects error at data link?", options: ["CRC", "Parity", "Checksum", "All"], answer: "All" },
      { q: "Which uses subnet mask?", options: ["IP", "TCP", "UDP", "ARP"], answer: "IP" },
      { q: "Which protocol supports QoS?", options: ["RSVP", "DNS", "ICMP", "SMTP"], answer: "RSVP" },
      { q: "Which layer handles authentication?", options: ["Presentation", "Session", "Transport", "Application"], answer: "Session" },
      { q: "Which routing uses AS number?", options: ["BGP", "RIP", "OSPF", "IGRP"], answer: "BGP" },
      { q: "Which is hybrid topology?", options: ["Star-Ring", "Bus", "Ring", "Mesh"], answer: "Star-Ring" },
      { q: "Which protocol uses port 22?", options: ["SSH", "FTP", "HTTP", "SMTP"], answer: "SSH" },
      { q: "Which layer handles framing?", options: ["Data Link", "Network", "Transport", "Physical"], answer: "Data Link" },
      { q: "Which protocol supports multicast?", options: ["IGMP", "ICMP", "ARP", "SMTP"], answer: "IGMP" },
      { q: "Which is loop prevention?", options: ["STP", "ARP", "DNS", "ICMP"], answer: "STP" },
      { q: "Which device works at Layer 7?", options: ["Gateway", "Router", "Switch", "Repeater"], answer: "Gateway" }
    ]
  },

  /* ===================== DBMS ===================== */
  dbms: {
    easy: [
      { q: "DBMS stands for?", options: ["Database Management System", "Data Backup System", "Database Machine Software", "None"], answer: "Database Management System" },
      { q: "Which is RDBMS?", options: ["MongoDB", "MySQL", "Redis", "Cassandra"], answer: "MySQL" },
      { q: "Which command retrieves data?", options: ["SELECT", "INSERT", "DELETE", "UPDATE"], answer: "SELECT" },
      { q: "Which key uniquely identifies row?", options: ["Foreign", "Primary", "Candidate", "Composite"], answer: "Primary" },
      { q: "Which stores data?", options: ["Table", "View", "Index", "Trigger"], answer: "Table" },
      { q: "Which removes duplicates?", options: ["DISTINCT", "WHERE", "GROUP BY", "ORDER BY"], answer: "DISTINCT" },
      { q: "Which joins tables?", options: ["JOIN", "MERGE", "UNION", "INTERSECT"], answer: "JOIN" },
      { q: "Which clause filters rows?", options: ["WHERE", "HAVING", "ORDER BY", "GROUP BY"], answer: "WHERE" },
      { q: "Which sorts data?", options: ["ORDER BY", "GROUP BY", "HAVING", "WHERE"], answer: "ORDER BY" },
      { q: "Which deletes table?", options: ["DROP", "DELETE", "TRUNCATE", "REMOVE"], answer: "DROP" },
      { q: "Which adds record?", options: ["INSERT", "ADD", "PUT", "CREATE"], answer: "INSERT" },
      { q: "Which modifies data?", options: ["UPDATE", "ALTER", "CHANGE", "SET"], answer: "UPDATE" },
      { q: "Which creates table?", options: ["CREATE", "BUILD", "MAKE", "FORM"], answer: "CREATE" },
      { q: "Which ensures uniqueness?", options: ["UNIQUE", "NOT NULL", "CHECK", "DEFAULT"], answer: "UNIQUE" },
      { q: "Which allows NULL?", options: ["DEFAULT", "CHECK", "NULL", "NOT NULL"], answer: "NULL" },
      { q: "Which is DDL?", options: ["CREATE", "SELECT", "INSERT", "UPDATE"], answer: "CREATE" },
      { q: "Which is DML?", options: ["INSERT", "DROP", "ALTER", "CREATE"], answer: "INSERT" },
      { q: "Which database is NoSQL?", options: ["Oracle", "MySQL", "MongoDB", "Postgres"], answer: "MongoDB" },
      { q: "Which ensures referential integrity?", options: ["Foreign Key", "Primary Key", "Index", "View"], answer: "Foreign Key" },
      { q: "Which displays data?", options: ["SELECT", "SHOW", "PRINT", "DISPLAY"], answer: "SELECT" }
    ],

    medium: [
      { q: "1NF removes?", options: ["Redundancy", "Partial dependency", "Repeating groups", "Transitive dependency"], answer: "Repeating groups" },
      { q: "2NF removes?", options: ["Repeating groups", "Partial dependency", "Transitive dependency", "Redundancy"], answer: "Partial dependency" },
      { q: "3NF removes?", options: ["Partial dependency", "Repeating groups", "Transitive dependency", "None"], answer: "Transitive dependency" },
      { q: "Which join returns all rows?", options: ["Inner", "Left", "Cross", "Self"], answer: "Left" },
      { q: "Which function counts rows?", options: ["COUNT()", "SUM()", "AVG()", "MAX()"], answer: "COUNT()" },
      { q: "Which is aggregate function?", options: ["SUM()", "UPPER()", "LOWER()", "ROUND()"], answer: "SUM()" },
      { q: "Which operator matches pattern?", options: ["LIKE", "IN", "BETWEEN", "ANY"], answer: "LIKE" },
      { q: "Which clause groups rows?", options: ["GROUP BY", "WHERE", "HAVING", "ORDER BY"], answer: "GROUP BY" },
      { q: "Which filters groups?", options: ["HAVING", "WHERE", "GROUP BY", "ORDER BY"], answer: "HAVING" },
      { q: "Which ensures atomicity?", options: ["Transaction", "Index", "View", "Trigger"], answer: "Transaction" },
      { q: "Which starts transaction?", options: ["BEGIN", "START", "OPEN", "INIT"], answer: "BEGIN" },
      { q: "Which saves transaction?", options: ["COMMIT", "SAVE", "STORE", "END"], answer: "COMMIT" },
      { q: "Which undoes changes?", options: ["ROLLBACK", "UNDO", "REVERT", "BACK"], answer: "ROLLBACK" },
      { q: "Which index improves search?", options: ["B-Tree", "Heap", "Stack", "Queue"], answer: "B-Tree" },
      { q: "Which view stores no data?", options: ["View", "Table", "Index", "Trigger"], answer: "View" },
      { q: "Which constraint checks condition?", options: ["CHECK", "UNIQUE", "DEFAULT", "NULL"], answer: "CHECK" },
      { q: "Which command removes rows?", options: ["DELETE", "DROP", "TRUNCATE", "REMOVE"], answer: "DELETE" },
      { q: "Which removes all rows fast?", options: ["TRUNCATE", "DELETE", "DROP", "CLEAR"], answer: "TRUNCATE" },
      { q: "Which ensures consistency?", options: ["ACID", "JOIN", "INDEX", "VIEW"], answer: "ACID" },
      { q: "Which DB supports ACID?", options: ["MySQL", "Redis", "MongoDB", "Cassandra"], answer: "MySQL" }
    ],

    hard: [
      { q: "Which normal form removes multivalued dependency?", options: ["3NF", "BCNF", "4NF", "5NF"], answer: "4NF" },
      { q: "BCNF stronger than?", options: ["3NF", "2NF", "1NF", "4NF"], answer: "3NF" },
      { q: "Which index fastest?", options: ["Hash", "B-Tree", "Bitmap", "Cluster"], answer: "Hash" },
      { q: "Which isolation level avoids phantom read?", options: ["Serializable", "Repeatable", "Read committed", "Read uncommitted"], answer: "Serializable" },
      { q: "Which schedule is serializable?", options: ["Conflict", "View", "Both", "None"], answer: "Both" },
      { q: "Which locking avoids deadlock?", options: ["Two-phase", "Timestamp", "Binary", "Shared"], answer: "Timestamp" },
      { q: "Which join expensive?", options: ["Nested loop", "Hash", "Merge", "Index"], answer: "Nested loop" },
      { q: "Which handles concurrency?", options: ["Transaction", "Index", "View", "Join"], answer: "Transaction" },
      { q: "Which anomaly in dirty read?", options: ["Read uncommitted", "Read committed", "Repeatable", "Serializable"], answer: "Read uncommitted" },
      { q: "Which ensures durability?", options: ["Log", "Index", "View", "Trigger"], answer: "Log" },
      { q: "Which DB supports sharding?", options: ["MongoDB", "MySQL", "Postgres", "Oracle"], answer: "MongoDB" },
      { q: "Which key is minimal superkey?", options: ["Candidate", "Primary", "Foreign", "Composite"], answer: "Candidate" },
      { q: "Which supports recursive queries?", options: ["CTE", "JOIN", "VIEW", "INDEX"], answer: "CTE" },
      { q: "Which is OLAP?", options: ["Data Warehouse", "OLTP", "CRUD", "Index"], answer: "Data Warehouse" },
      { q: "Which join uses equality?", options: ["Equi Join", "Theta Join", "Cross Join", "Outer Join"], answer: "Equi Join" },
      { q: "Which query optimization uses cost?", options: ["Cost-based", "Rule-based", "Heuristic", "Static"], answer: "Cost-based" },
      { q: "Which ensures atomic commit?", options: ["Two-phase commit", "Locking", "Indexing", "Sharding"], answer: "Two-phase commit" },
      { q: "Which isolation level fastest?", options: ["Read uncommitted", "Read committed", "Repeatable", "Serializable"], answer: "Read uncommitted" },
      { q: "Which anomaly phantom read?", options: ["New rows appear", "Data mismatch", "Lost update", "Dirty read"], answer: "New rows appear" },
      { q: "Which DB uses CAP theorem?", options: ["NoSQL", "RDBMS", "OLAP", "File System"], answer: "NoSQL" }
    ]
  },
  os: {
  easy: [
    { q: "OS stands for?", options: ["Operating System", "Open Software", "Online System", "Order System"], answer: "Operating System" },
    { q: "Which is OS?", options: ["Linux", "HTML", "CSS", "SQL"], answer: "Linux" },
    { q: "Brain of OS?", options: ["Kernel", "Shell", "CPU", "RAM"], answer: "Kernel" },
    { q: "Which manages memory?", options: ["Compiler", "OS", "CPU", "Cache"], answer: "OS" },
    { q: "Which is multitasking OS?", options: ["DOS", "Windows", "BIOS", "Firmware"], answer: "Windows" },
    { q: "Which is single-user OS?", options: ["Linux", "Windows", "DOS", "Unix"], answer: "DOS" },
    { q: "Which is not OS?", options: ["Linux", "Unix", "Oracle", "Windows"], answer: "Oracle" },
    { q: "Which handles process?", options: ["Kernel", "Shell", "File", "User"], answer: "Kernel" },
    { q: "Which is volatile memory?", options: ["ROM", "RAM", "SSD", "HDD"], answer: "RAM" },
    { q: "Which is scheduling?", options: ["Process management", "File system", "Security", "Networking"], answer: "Process management" },
    { q: "Which is system call?", options: ["fork()", "printf()", "cin", "cout"], answer: "fork()" },
    { q: "Which is not OS service?", options: ["File access", "Process control", "Compilation", "Security"], answer: "Compilation" },
    { q: "Which executes first?", options: ["Kernel", "BIOS", "Shell", "User"], answer: "BIOS" },
    { q: "Which manages files?", options: ["File system", "Memory", "CPU", "Scheduler"], answer: "File system" },
    { q: "Which supports concurrency?", options: ["Multithreading", "Single task", "Batch", "Sequential"], answer: "Multithreading" },
    { q: "Which OS is open source?", options: ["Linux", "Windows", "macOS", "DOS"], answer: "Linux" },
    { q: "Which handles interrupts?", options: ["CPU", "Kernel", "User", "Shell"], answer: "Kernel" },
    { q: "Which OS used in servers?", options: ["Linux", "DOS", "BIOS", "Firmware"], answer: "Linux" },
    { q: "Which OS supports GUI?", options: ["Windows", "DOS", "Unix", "BIOS"], answer: "Windows" },
    { q: "Which is not scheduling algorithm?", options: ["FCFS", "SJF", "Round Robin", "DFS"], answer: "DFS" }
  ],

  medium: [
    { q: "Which scheduling is preemptive?", options: ["FCFS", "SJF", "Round Robin", "Priority (non)"], answer: "Round Robin" },
    { q: "Which causes deadlock?", options: ["Circular wait", "Paging", "Segmentation", "Caching"], answer: "Circular wait" },
    { q: "Which avoids starvation?", options: ["Aging", "Paging", "Spooling", "Swapping"], answer: "Aging" },
    { q: "Which is context switch?", options: ["CPU state change", "Memory swap", "File open", "Disk access"], answer: "CPU state change" },
    { q: "Which algorithm minimum avg waiting?", options: ["SJF", "FCFS", "RR", "Priority"], answer: "SJF" },
    { q: "Which memory allocation fastest?", options: ["First fit", "Best fit", "Worst fit", "Next fit"], answer: "First fit" },
    { q: "Which page replacement optimal?", options: ["FIFO", "LRU", "Optimal", "Clock"], answer: "Optimal" },
    { q: "Which is virtual memory?", options: ["Secondary memory", "RAM", "Cache", "Register"], answer: "Secondary memory" },
    { q: "Which causes thrashing?", options: ["High paging", "Low memory", "Low CPU", "Disk failure"], answer: "High paging" },
    { q: "Which is semaphore?", options: ["Sync tool", "Scheduling", "Memory", "File"], answer: "Sync tool" },
    { q: "Which uses time quantum?", options: ["RR", "SJF", "FCFS", "Priority"], answer: "RR" },
    { q: "Which is critical section?", options: ["Shared code", "User code", "Kernel code", "Idle code"], answer: "Shared code" },
    { q: "Which is IPC?", options: ["Pipe", "File", "Cache", "Register"], answer: "Pipe" },
    { q: "Which system avoids deadlock?", options: ["Banker's", "FIFO", "LRU", "FCFS"], answer: "Banker's" },
    { q: "Which is spooling?", options: ["Buffering", "Scheduling", "Paging", "Segmentation"], answer: "Buffering" },
    { q: "Which memory is fastest?", options: ["Register", "Cache", "RAM", "Disk"], answer: "Register" },
    { q: "Which is real-time OS?", options: ["RTOS", "Linux", "Windows", "DOS"], answer: "RTOS" },
    { q: "Which is kernel mode?", options: ["Privileged", "User", "Guest", "Idle"], answer: "Privileged" },
    { q: "Which handles synchronization?", options: ["Semaphore", "Paging", "Cache", "Disk"], answer: "Semaphore" },
    { q: "Which OS uses microkernel?", options: ["Mach", "Linux", "Windows", "DOS"], answer: "Mach" }
  ],

  hard: [
    { q: "Which deadlock condition removable?", options: ["Circular wait", "Hold and wait", "Mutual exclusion", "No preemption"], answer: "Hold and wait" },
    { q: "Which page replacement least faults?", options: ["Optimal", "LRU", "FIFO", "Clock"], answer: "Optimal" },
    { q: "Which scheduling starvation?", options: ["Priority", "RR", "FCFS", "SJF"], answer: "Priority" },
    { q: "Which memory technique avoids fragmentation?", options: ["Paging", "Segmentation", "Swapping", "Caching"], answer: "Paging" },
    { q: "Which IPC fastest?", options: ["Shared memory", "Pipe", "Message queue", "Socket"], answer: "Shared memory" },
    { q: "Which is soft real-time?", options: ["Linux", "RTOS", "DOS", "BIOS"], answer: "Linux" },
    { q: "Which scheduling minimizes response time?", options: ["SJF", "FCFS", "RR", "Priority"], answer: "SJF" },
    { q: "Which memory uses page table?", options: ["Virtual", "Cache", "RAM", "Register"], answer: "Virtual" },
    { q: "Which is Belady’s anomaly?", options: ["More frames more faults", "Deadlock", "Starvation", "Thrashing"], answer: "More frames more faults" },
    { q: "Which uses TLB?", options: ["Paging", "Segmentation", "Swapping", "Scheduling"], answer: "Paging" },
    { q: "Which scheduling NP-hard?", options: ["Multiprocessor", "FCFS", "RR", "FIFO"], answer: "Multiprocessor" },
    { q: "Which uses spinlock?", options: ["Multicore", "Uniprocessor", "Batch", "Sequential"], answer: "Multicore" },
    { q: "Which OS supports containers?", options: ["Linux", "DOS", "BIOS", "RTOS"], answer: "Linux" },
    { q: "Which avoids race condition?", options: ["Mutex", "Paging", "Caching", "Swapping"], answer: "Mutex" },
    { q: "Which algorithm deadlock avoidance?", options: ["Banker’s", "FIFO", "LRU", "SJF"], answer: "Banker’s" },
    { q: "Which memory uses locality?", options: ["Cache", "Disk", "Register", "ROM"], answer: "Cache" },
    { q: "Which supports SMP?", options: ["Linux", "DOS", "BIOS", "Firmware"], answer: "Linux" },
    { q: "Which scheduling fairness?", options: ["RR", "FCFS", "Priority", "SJF"], answer: "RR" },
    { q: "Which file allocation avoids fragmentation?", options: ["Indexed", "Contiguous", "Linked", "Static"], answer: "Indexed" },
    { q: "Which OS is distributed?", options: ["Amoeba", "DOS", "BIOS", "RTOS"], answer: "Amoeba" }
  ]
},

math: {
  easy: [
    { q: "Probability range?", options: ["0 to 1", "0 to 100", "-1 to 1", "1 to 10"], answer: "0 to 1" },
    { q: "Mean of 2,4,6?", options: ["4", "5", "6", "8"], answer: "4" },
    { q: "Median of 1,3,5?", options: ["1", "3", "5", "4"], answer: "3" },
    { q: "Matrix order 2x3 has?", options: ["6 elements", "5", "4", "3"], answer: "6 elements" },
    { q: "Determinant of 1x1?", options: ["Element", "0", "1", "Undefined"], answer: "Element" },
    { q: "P(A)=0.5, fair coin?", options: ["Yes", "No", "Maybe", "None"], answer: "Yes" },
    { q: "Mode is?", options: ["Most frequent", "Average", "Middle", "Range"], answer: "Most frequent" },
    { q: "Identity matrix diagonal?", options: ["1", "0", "-1", "Any"], answer: "1" },
    { q: "Linear equation degree?", options: ["1", "2", "3", "0"], answer: "1" },
    { q: "Vector magnitude formula?", options: ["√(x²+y²)", "x+y", "x−y", "x×y"], answer: "√(x²+y²)" },
    { q: "Mean symbol?", options: ["μ", "σ", "λ", "θ"], answer: "μ" },
    { q: "Standard deviation shows?", options: ["Spread", "Center", "Sum", "Product"], answer: "Spread" },
    { q: "Transpose flips?", options: ["Rows & columns", "Elements", "Values", "Signs"], answer: "Rows & columns" },
    { q: "Probability of sure event?", options: ["1", "0", "0.5", "-1"], answer: "1" },
    { q: "Scalar has?", options: ["Magnitude only", "Direction", "Both", "None"], answer: "Magnitude only" },
    { q: "Matrix addition possible when?", options: ["Same order", "Any", "Square", "Diagonal"], answer: "Same order" },
    { q: "Variance is square of?", options: ["SD", "Mean", "Mode", "Median"], answer: "SD" },
    { q: "Dot product gives?", options: ["Scalar", "Vector", "Matrix", "None"], answer: "Scalar" },
    { q: "Probability sum of sample space?", options: ["1", "0", "∞", "-1"], answer: "1" },
    { q: "Rank of identity matrix?", options: ["n", "1", "0", "Undefined"], answer: "n" }
  ],

  medium: [
    { q: "Bayes theorem used for?", options: ["Conditional probability", "Mean", "Variance", "Matrix"], answer: "Conditional probability" },
    { q: "Expected value formula?", options: ["Σxp", "Σx", "Σp", "Σx²"], answer: "Σxp" },
    { q: "Determinant zero means?", options: ["Singular", "Identity", "Diagonal", "Invertible"], answer: "Singular" },
    { q: "Correlation coefficient range?", options: ["-1 to 1", "0 to 1", "-∞ to ∞", "1 to 10"], answer: "-1 to 1" },
    { q: "Eigenvalues from?", options: ["|A−λI|=0", "A+Aᵀ", "A²", "A⁻¹"], answer: "|A−λI|=0" },
    { q: "Random variable type?", options: ["Discrete", "Continuous", "Both", "None"], answer: "Both" },
    { q: "Mean deviation measured from?", options: ["Mean", "Median", "Mode", "All"], answer: "All" },
    { q: "Variance formula?", options: ["σ²", "σ", "μ", "λ"], answer: "σ²" },
    { q: "Orthogonal vectors dot product?", options: ["0", "1", "-1", "∞"], answer: "0" },
    { q: "Probability density integrates to?", options: ["1", "0", "∞", "-1"], answer: "1" },
    { q: "Singular matrix inverse?", options: ["Not exists", "Exists", "Partial", "Zero"], answer: "Not exists" },
    { q: "Poisson distribution parameter?", options: ["λ", "μ", "σ", "θ"], answer: "λ" },
    { q: "Mean of normal distribution?", options: ["μ", "σ", "0", "1"], answer: "μ" },
    { q: "Covariance sign shows?", options: ["Direction", "Magnitude", "Scale", "Units"], answer: "Direction" },
    { q: "Rank equals?", options: ["Non-zero rows", "Columns", "Diagonal", "Trace"], answer: "Non-zero rows" },
    { q: "Vector cross product gives?", options: ["Vector", "Scalar", "Matrix", "None"], answer: "Vector" },
    { q: "Standard normal mean?", options: ["0", "1", "-1", "∞"], answer: "0" },
    { q: "Conditional probability formula?", options: ["P(A∩B)/P(B)", "P(A)/P(B)", "P(B)/P(A)", "P(A+B)"], answer: "P(A∩B)/P(B)" },
    { q: "Linear independence means?", options: ["No combination", "Equal", "Same", "Multiple"], answer: "No combination" },
    { q: "Trace of matrix?", options: ["Sum of diagonal", "Product", "Rank", "Determinant"], answer: "Sum of diagonal" }
  ],

  hard: [
    { q: "Markov property means?", options: ["Memoryless", "Dependent", "Independent", "Random"], answer: "Memoryless" },
    { q: "MLE used to estimate?", options: ["Parameters", "Mean", "Variance", "Range"], answer: "Parameters" },
    { q: "Central limit theorem applies to?", options: ["Large samples", "Small samples", "Single value", "None"], answer: "Large samples" },
    { q: "Orthogonal matrix inverse?", options: ["Transpose", "Determinant", "Adjoint", "Identity"], answer: "Transpose" },
    { q: "Chi-square tests?", options: ["Independence", "Mean", "Variance", "Correlation"], answer: "Independence" },
    { q: "Jacobian used in?", options: ["Transformation", "Integration", "Differentiation", "Limits"], answer: "Transformation" },
    { q: "Covariance zero means?", options: ["Uncorrelated", "Independent", "Same", "Equal"], answer: "Uncorrelated" },
    { q: "Eigenvectors satisfy?", options: ["Ax=λx", "Ax=0", "A=x", "Aλ=x"], answer: "Ax=λx" },
    { q: "Gaussian distribution shape?", options: ["Bell", "Flat", "Linear", "Exponential"], answer: "Bell" },
    { q: "Variance of sum independent?", options: ["Sum of variances", "Product", "Difference", "Mean"], answer: "Sum of variances" },
    { q: "Rank-nullity theorem?", options: ["Rank+Nullity=n", "Rank=n", "Nullity=n", "None"], answer: "Rank+Nullity=n" },
    { q: "Law of large numbers implies?", options: ["Convergence", "Divergence", "Variance", "Skewness"], answer: "Convergence" },
    { q: "Correlation −1 means?", options: ["Perfect negative", "None", "Weak", "Positive"], answer: "Perfect negative" },
    { q: "Determinant geometrically?", options: ["Area/Volume", "Length", "Angle", "Direction"], answer: "Area/Volume" },
    { q: "Moment generating function used for?", options: ["Moments", "Mean only", "Variance only", "None"], answer: "Moments" },
    { q: "PCA reduces?", options: ["Dimensionality", "Accuracy", "Data", "Noise"], answer: "Dimensionality" },
    { q: "Normal distribution skewness?", options: ["0", "1", "-1", "∞"], answer: "0" },
    { q: "Confidence interval shows?", options: ["Range", "Exact", "Point", "Variance"], answer: "Range" },
    { q: "Hypothesis testing error type I?", options: ["False positive", "False negative", "Correct", "None"], answer: "False positive" },
    { q: "Orthogonality implies?", options: ["Zero dot product", "Same vector", "Parallel", "Magnitude"], answer: "Zero dot product" }
  ]
},
sports: {
  easy: [
    { q: "National sport of India?", options: ["Cricket", "Hockey", "Football", "Kabaddi"], answer: "Hockey" },
    { q: "Players in a cricket team?", options: ["9", "10", "11", "12"], answer: "11" },
    { q: "Football World Cup held every?", options: ["2 years", "3 years", "4 years", "5 years"], answer: "4 years" },
    { q: "Olympics symbol has rings?", options: ["4", "5", "6", "7"], answer: "5" },
    { q: "Tennis uses?", options: ["Bat", "Racket", "Stick", "Club"], answer: "Racket" },
    { q: "Sachin Tendulkar belongs to?", options: ["Football", "Cricket", "Tennis", "Hockey"], answer: "Cricket" },
    { q: "Badminton uses?", options: ["Ball", "Shuttlecock", "Bat", "Stick"], answer: "Shuttlecock" },
    { q: "Which is indoor game?", options: ["Cricket", "Football", "Chess", "Hockey"], answer: "Chess" },
    { q: "IPL is related to?", options: ["Football", "Cricket", "Hockey", "Tennis"], answer: "Cricket" },
    { q: "MS Dhoni is famous for?", options: ["Hockey", "Cricket", "Tennis", "Football"], answer: "Cricket" },
    { q: "Which sport uses net?", options: ["Cricket", "Badminton", "Boxing", "Chess"], answer: "Badminton" },
    { q: "Kabaddi team size?", options: ["5", "6", "7", "8"], answer: "7" },
    { q: "Wimbledon is related to?", options: ["Cricket", "Football", "Tennis", "Golf"], answer: "Tennis" },
    { q: "Which sport uses gloves?", options: ["Cricket", "Boxing", "Tennis", "Golf"], answer: "Boxing" },
    { q: "FIFA is related to?", options: ["Cricket", "Football", "Hockey", "Tennis"], answer: "Football" },
    { q: "Which sport has penalty kick?", options: ["Cricket", "Football", "Hockey", "Tennis"], answer: "Football" },
    { q: "Which country hosts IPL?", options: ["Australia", "India", "England", "SA"], answer: "India" },
    { q: "Which sport uses wickets?", options: ["Football", "Cricket", "Tennis", "Golf"], answer: "Cricket" },
    { q: "World Cup trophy Jules Rimet belongs to?", options: ["Cricket", "Football", "Hockey", "Tennis"], answer: "Football" },
    { q: "Which is water sport?", options: ["Hockey", "Swimming", "Cricket", "Kabaddi"], answer: "Swimming" }
  ],

  medium: [
    { q: "How many overs in ODI cricket?", options: ["20", "40", "50", "60"], answer: "50" },
    { q: "Which country won first Cricket World Cup?", options: ["India", "Australia", "West Indies", "England"], answer: "West Indies" },
    { q: "Which Grand Slam played on grass?", options: ["US Open", "French Open", "Wimbledon", "Australian Open"], answer: "Wimbledon" },
    { q: "Offside rule is in?", options: ["Cricket", "Football", "Hockey", "Kabaddi"], answer: "Football" },
    { q: "Which country hosts Tour de France?", options: ["Italy", "France", "Spain", "Germany"], answer: "France" },
    { q: "Hat-trick means?", options: ["3 goals", "2 goals", "4 goals", "5 goals"], answer: "3 goals" },
    { q: "Which sport has LBW?", options: ["Football", "Cricket", "Tennis", "Golf"], answer: "Cricket" },
    { q: "Which is oldest Olympic sport?", options: ["Running", "Swimming", "Wrestling", "Boxing"], answer: "Wrestling" },
    { q: "Maximum players in basketball team on court?", options: ["5", "6", "7", "8"], answer: "5" },
    { q: "Which country invented badminton?", options: ["India", "England", "China", "Japan"], answer: "England" },
    { q: "Which sport uses clay court?", options: ["Tennis", "Football", "Hockey", "Golf"], answer: "Tennis" },
    { q: "Which cup is hockey world cup?", options: ["Davis Cup", "Webb Ellis Cup", "Hockey WC", "None"], answer: "Hockey WC" },
    { q: "Which Indian won Olympic gold in javelin?", options: ["Abhinav Bindra", "Neeraj Chopra", "Milkha Singh", "PV Sindhu"], answer: "Neeraj Chopra" },
    { q: "Which country dominates table tennis?", options: ["India", "China", "Japan", "Korea"], answer: "China" },
    { q: "Which sport uses deuce?", options: ["Tennis", "Cricket", "Football", "Hockey"], answer: "Tennis" },
    { q: "Which football club has most UCL titles?", options: ["Barcelona", "Real Madrid", "AC Milan", "Bayern"], answer: "Real Madrid" },
    { q: "Which sport uses knockout format?", options: ["Cricket", "Football", "Both", "None"], answer: "Both" },
    { q: "Which country hosts Olympics 2021?", options: ["China", "Japan", "Brazil", "UK"], answer: "Japan" },
    { q: "Which sport uses rings?", options: ["Gymnastics", "Boxing", "Wrestling", "Judo"], answer: "Gymnastics" },
    { q: "Which award for best footballer?", options: ["Ballon d'Or", "Golden Bat", "Laureus", "Oscar"], answer: "Ballon d'Or" }
  ],

  hard: [
    { q: "Duckworth–Lewis method used in?", options: ["Football", "Cricket", "Hockey", "Tennis"], answer: "Cricket" },
    { q: "Which country won most FIFA World Cups?", options: ["Germany", "Italy", "Brazil", "Argentina"], answer: "Brazil" },
    { q: "First modern Olympics held in?", options: ["Paris", "Athens", "London", "Rome"], answer: "Athens" },
    { q: "Which tennis player won most Grand Slams?", options: ["Federer", "Nadal", "Djokovic", "Sampras"], answer: "Djokovic" },
    { q: "Which cricket format introduced first?", options: ["Test", "ODI", "T20", "Hundred"], answer: "Test" },
    { q: "Which country hosted 2016 Olympics?", options: ["China", "Brazil", "UK", "Japan"], answer: "Brazil" },
    { q: "Which Indian woman won Olympic medal in badminton?", options: ["Saina Nehwal", "PV Sindhu", "Both", "None"], answer: "Both" },
    { q: "Which footballer has most Ballon d'Or?", options: ["Messi", "Ronaldo", "Cruyff", "Ronaldinho"], answer: "Messi" },
    { q: "Which country won 2011 Cricket World Cup?", options: ["Australia", "India", "Sri Lanka", "England"], answer: "India" },
    { q: "Which sport uses VAR?", options: ["Cricket", "Football", "Tennis", "Hockey"], answer: "Football" },
    { q: "Which sport has Ryder Cup?", options: ["Golf", "Tennis", "Cricket", "Football"], answer: "Golf" },
    { q: "Which country won most Olympic golds?", options: ["China", "USA", "Russia", "UK"], answer: "USA" },
    { q: "Which stadium called Mecca of cricket?", options: ["Lords", "MCG", "Eden Gardens", "Wankhede"], answer: "Lords" },
    { q: "Which Indian won first Olympic gold?", options: ["Abhinav Bindra", "KD Jadhav", "Milkha Singh", "PT Usha"], answer: "Abhinav Bindra" },
    { q: "Which sport banned bodyline?", options: ["Cricket", "Football", "Hockey", "Tennis"], answer: "Cricket" },
    { q: "Which country won Euro 2020?", options: ["France", "England", "Italy", "Portugal"], answer: "Italy" },
    { q: "Which sport has terms birdie & eagle?", options: ["Golf", "Cricket", "Hockey", "Tennis"], answer: "Golf" },
    { q: "Which nation hosts Super Bowl?", options: ["UK", "USA", "Canada", "Australia"], answer: "USA" },
    { q: "Which Olympic motto?", options: ["Faster Higher Stronger", "Just Do It", "Play Fair", "Unity"], answer: "Faster Higher Stronger" },
    { q: "Which cricket player scored 400* in Test?", options: ["Sachin", "Sehwag", "Brian Lara", "Ponting"], answer: "Brian Lara" }
  ]
},
general: {
  easy: [
    { q: "Capital of India?", options: ["Mumbai", "Delhi", "Kolkata", "Chennai"], answer: "Delhi" },
    { q: "National animal of India?", options: ["Lion", "Tiger", "Elephant", "Leopard"], answer: "Tiger" },
    { q: "Largest planet in solar system?", options: ["Earth", "Mars", "Jupiter", "Saturn"], answer: "Jupiter" },
    { q: "Currency of India?", options: ["Dollar", "Euro", "Rupee", "Yen"], answer: "Rupee" },
    { q: "Father of Indian Constitution?", options: ["Gandhi", "Nehru", "Ambedkar", "Patel"], answer: "Ambedkar" },
    { q: "National bird of India?", options: ["Sparrow", "Peacock", "Crow", "Eagle"], answer: "Peacock" },
    { q: "Largest ocean?", options: ["Indian", "Atlantic", "Pacific", "Arctic"], answer: "Pacific" },
    { q: "Who discovered gravity?", options: ["Einstein", "Newton", "Galileo", "Tesla"], answer: "Newton" },
    { q: "How many continents?", options: ["5", "6", "7", "8"], answer: "7" },
    { q: "Which gas plants absorb?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: "Carbon Dioxide" },
    { q: "National flower of India?", options: ["Rose", "Lotus", "Lily", "Sunflower"], answer: "Lotus" },
    { q: "Largest mammal?", options: ["Elephant", "Blue Whale", "Shark", "Giraffe"], answer: "Blue Whale" },
    { q: "Sun rises in?", options: ["North", "South", "East", "West"], answer: "East" },
    { q: "Which is longest river?", options: ["Amazon", "Nile", "Ganga", "Yangtze"], answer: "Nile" },
    { q: "How many days in leap year?", options: ["365", "366", "364", "367"], answer: "366" },
    { q: "Who invented telephone?", options: ["Edison", "Bell", "Tesla", "Newton"], answer: "Bell" },
    { q: "Largest desert?", options: ["Sahara", "Gobi", "Thar", "Arabian"], answer: "Sahara" },
    { q: "National tree of India?", options: ["Neem", "Banyan", "Peepal", "Mango"], answer: "Banyan" },
    { q: "Which organ pumps blood?", options: ["Brain", "Liver", "Heart", "Lungs"], answer: "Heart" },
    { q: "Rainbow has how many colors?", options: ["5", "6", "7", "8"], answer: "7" }
  ],

  medium: [
    { q: "Who is known as Iron Man of India?", options: ["Gandhi", "Patel", "Nehru", "Bose"], answer: "Patel" },
    { q: "Which planet is known as Red Planet?", options: ["Earth", "Venus", "Mars", "Jupiter"], answer: "Mars" },
    { q: "Which amendment lowered voting age to 18?", options: ["42nd", "44th", "61st", "73rd"], answer: "61st" },
    { q: "Which is largest democracy?", options: ["USA", "India", "UK", "France"], answer: "India" },
    { q: "Which metal is liquid at room temp?", options: ["Iron", "Mercury", "Aluminium", "Silver"], answer: "Mercury" },
    { q: "Who wrote Ramayana?", options: ["Valmiki", "Vyasa", "Tulsidas", "Kalidas"], answer: "Valmiki" },
    { q: "Which is highest mountain?", options: ["K2", "Everest", "Kilimanjaro", "Denali"], answer: "Everest" },
    { q: "Which country has most population?", options: ["India", "China", "USA", "Russia"], answer: "India" },
    { q: "Which blood group universal donor?", options: ["A", "B", "AB", "O"], answer: "O" },
    { q: "Which vitamin from sunlight?", options: ["A", "B", "C", "D"], answer: "D" },
    { q: "Who is head of state in India?", options: ["PM", "President", "CM", "Governor"], answer: "President" },
    { q: "Which country gifted Statue of Liberty?", options: ["UK", "France", "Germany", "Italy"], answer: "France" },
    { q: "Which is smallest bone?", options: ["Femur", "Stapes", "Ulna", "Radius"], answer: "Stapes" },
    { q: "Which is not renewable?", options: ["Solar", "Wind", "Coal", "Hydro"], answer: "Coal" },
    { q: "Who founded Mughal Empire?", options: ["Akbar", "Babur", "Humayun", "Aurangzeb"], answer: "Babur" },
    { q: "Which sea separates India & Sri Lanka?", options: ["Arabian Sea", "Bay of Bengal", "Red Sea", "Palk Strait"], answer: "Palk Strait" },
    { q: "Which gas used in balloons?", options: ["Oxygen", "Nitrogen", "Helium", "Hydrogen"], answer: "Helium" },
    { q: "Which is longest constitution?", options: ["USA", "UK", "India", "China"], answer: "India" },
    { q: "Who wrote national anthem?", options: ["Bankim", "Tagore", "Nehru", "Patel"], answer: "Tagore" },
    { q: "Which organ purifies blood?", options: ["Heart", "Liver", "Kidney", "Lung"], answer: "Kidney" }
  ],

  hard: [
    { q: "Which article deals with emergency?", options: ["352", "356", "360", "All"], answer: "All" },
    { q: "Who is known as Father of Economics?", options: ["Keynes", "Marshall", "Adam Smith", "Ricardo"], answer: "Adam Smith" },
    { q: "Which country first launched satellite?", options: ["USA", "USSR", "China", "UK"], answer: "USSR" },
    { q: "Which is deepest ocean trench?", options: ["Java", "Mariana", "Tonga", "Philippine"], answer: "Mariana" },
    { q: "Which Indian state has longest coastline?", options: ["Kerala", "Tamil Nadu", "Gujarat", "Andhra"], answer: "Gujarat" },
    { q: "Who introduced decimal system?", options: ["Aryabhata", "Newton", "Einstein", "Galileo"], answer: "Aryabhata" },
    { q: "Which organelle is powerhouse?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi"], answer: "Mitochondria" },
    { q: "Which year UN formed?", options: ["1942", "1945", "1950", "1960"], answer: "1945" },
    { q: "Which river crosses equator twice?", options: ["Amazon", "Congo", "Nile", "Yangtze"], answer: "Congo" },
    { q: "Who proposed theory of relativity?", options: ["Newton", "Einstein", "Tesla", "Bohr"], answer: "Einstein" },
    { q: "Which country left EU (Brexit)?", options: ["France", "Germany", "UK", "Italy"], answer: "UK" },
    { q: "Which Indian satellite for navigation?", options: ["INSAT", "IRS", "NAVIC", "GSAT"], answer: "NAVIC" },
    { q: "Which layer protects from UV?", options: ["Troposphere", "Ozone", "Stratosphere", "Ionosphere"], answer: "Ozone" },
    { q: "Which gas causes acid rain?", options: ["CO₂", "SO₂", "O₂", "N₂"], answer: "SO₂" },
    { q: "Who was first Governor General of India?", options: ["Clive", "Warren Hastings", "Dalhousie", "Curzon"], answer: "Warren Hastings" },
    { q: "Which is smallest continent?", options: ["Europe", "Australia", "Antarctica", "Africa"], answer: "Australia" },
    { q: "Which Indian missile is ICBM?", options: ["Agni-V", "Prithvi", "Akash", "BrahMos"], answer: "Agni-V" },
    { q: "Which summit deals climate change?", options: ["G20", "COP", "BRICS", "SAARC"], answer: "COP" },
    { q: "Which organ controls hormones?", options: ["Brain", "Pituitary", "Thyroid", "Adrenal"], answer: "Pituitary" },
    { q: "Which Indian city called Silicon Valley?", options: ["Hyderabad", "Chennai", "Bengaluru", "Pune"], answer: "Bengaluru" }
  ]
}


};

